
[[redirects]]
  from = "/api/*"
  force = true
  to = "https://payal-pvt-ltd.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

  [build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "16"
