sonar.projectKey=sqp_e53c7c241df5ba7d99333034d476d66f902deb42
sonar.projectName=PYL-PVT-KOLKATA
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.sources=backend,client

# Exclude build files
sonar.exclusions=node_modules/**,build/**,dist/**

# TypeScript support
sonar.typescript.tsconfigPath=backend/tsconfig.json,client/tsconfig.json
sonar.login=admin
sonar.password=sonarindranil
# Encoding
sonar.sourceEncoding=UTF-8